[build-system]
requires = ["setuptools>=68", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "minipam"
dynamic = ["version"]
description = "A minimalistic IPAM solution"
authors = [
  { name = "Remi Noel", email = "remi@rnoel.net" }
]
license = "MIT"
requires-python = ">=3.9"
dependencies = [

]

[project.optional-dependencies]
dev = [
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
minipam = # TODO: Define the entry point for the minipam CLI


[tool.setuptools_scm]


